<?php

$plugin_mcf['calendar']['backups']="enum:0.1,2,3,4,5,6,7,8,9,10";
$plugin_mcf['calendar']['calendar_shows_previous_and_next_month_button']="bool";
$plugin_mcf['calendar']['calendar_week_starts_monday']="bool";
$plugin_mcf['calendar']['calendar_weekend_day_1']="enum:0,1,2,3,4,5,6,7";
$plugin_mcf['calendar']['calendar_weekend_day_2']="enum:0,1,2,3,4,5,6,7";
$plugin_mcf['calendar']['date_delimiter']="enum:.,-,/";
$plugin_mcf['calendar']['date_picker']="bool";
$plugin_mcf['calendar']['editor']="string";
$plugin_mcf['calendar']['editor_deletes_empty_lines_at_the_end']="bool";
$plugin_mcf['calendar']['editor_height']="string";
$plugin_mcf['calendar']['eventlist_start_moves_with_clicked_event']="bool";
$plugin_mcf['calendar']['eventlist_template']="function:calendar_getTemplates";
$plugin_mcf['calendar']['filepath_calendar_background_images']="string";
$plugin_mcf['calendar']['filepath_data']="string";
$plugin_mcf['calendar']['input-field_additional_days_as_textarea']="string";
$plugin_mcf['calendar']['input-field_entry1_as_textarea']="bool";
$plugin_mcf['calendar']['input-field_entry1_show_in_input_always']="bool";
$plugin_mcf['calendar']['input-field_entry3_as_textarea']="string";
$plugin_mcf['calendar']['input-field_mainentry_as_textarea']="string";
$plugin_mcf['calendar']['popup_direction_big_calendar']="enum:,down,right,left";
$plugin_mcf['calendar']['popup_direction_small_calendar']="enum:,down,right,left";
$plugin_mcf['calendar']['same-event-calendar_for_all_subsites']="bool";
$plugin_mcf['calendar']['second-calendar_eventpage']="";
$plugin_mcf['calendar']['second-calendar_filename']="";
$plugin_mcf['calendar']['selectable_fonts']="text";
$plugin_mcf['calendar']['selectable_fontsizes']="text";
$plugin_mcf['calendar']['selectable_lineheights']="text";
$plugin_mcf['calendar']['style_headline_eventtype']="text";
$plugin_mcf['calendar']['style_headline_year']="text";
$plugin_mcf['calendar']['z-index']="string";

?>
